project_name: tdl
dist: .tdl/dist
env:
  - GO111MODULE=on
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/pkg/consts.Version={{ .Version }}
      - -X {{ .ModulePath }}/pkg/consts.Commit={{ .ShortCommit }}
      - -X {{ .ModulePath }}/pkg/consts.CommitDate={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - riscv64
      - loong64
    goarm:
      - 5
      - 6
      - 7
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README*.md
      - LICENSE
changelog:
  use: github
  sort: asc
  groups:
    - title: New Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: Others
      order: 4
release:
  draft: true
