package consts

const (
	FlagProxy         = "proxy"
	FlagNamespace     = "ns"
	FlagDebug         = "debug"
	FlagPartSize      = "size"
	FlagThreads       = "threads"
	FlagLimit         = "limit"
	FlagNTP           = "ntp"
	FlagUpPath        = "path"
	FlagUpExcludes    = "excludes"
	FlagLoginDesktop  = "desktop"
	FlagLoginPasscode = "passcode"
	FlagLoginCode     = "code"
	FlagDlUrl         = "url"
	FlagDlFile        = "file"
	FlagDlTemplate    = "template"
	FlagDlInclude     = "include"
	FlagDlExclude     = "exclude"
	FlagDlDesc        = "desc"
	FlagDlDir         = "dir"
	FlagDlRewriteExt  = "rewrite-ext"
	FlagDlSkipSame    = "skip-same"
	FlagDlPool        = "pool"
	FlagDlContinue    = "continue"
	FlagDlRestart     = "restart"
)
