name: docker

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to checkout'
        required: true
        default: 'master'
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: git
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=match,pattern=\d+.\d+.\d+
            type=ref,event=branch
            type=ref,event=pr
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.RELEASE_TOKEN }}
      - name: Use latest Dockerfile if workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          curl -s https://raw.githubusercontent.com/iyear/tdl/master/Dockerfile > Dockerfile
      - name: Extract Dockerfile args
        id: args
        run: |
          echo "commit=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "commit_date=$(git show -s --format=%cI)" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            COMMIT=${{ steps.args.outputs.commit }}
            COMMIT_DATE=${{ steps.args.outputs.commit_date }}
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6,linux/riscv64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
